CREATE TABLE [Setup].[ProductPriceInfo]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[ProductInfoId] UNIQUEIDENTIFIER NOT NULL,
	[Price] DECIMAL(12,3) NOT NULL,
	[SequenceId] INT NOT NULL IDENTITY,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[ModifiedBy] UNIQUEIDENTIFIER NULL,
	[ModifiedDate] DATETIME2,
	[RowStatus] NVARCHAR(1) NOT NULL DEFAULT 'A'
	CONSTRAINT [PK_Setup_ProductPriceInfo] PRIMARY KEY NONCLUSTERED
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_ProductPriceInfo_ProductInfo] FOREIGN KEY ([ProductInfoId]) REFERENCES [Setup].[ProductInfo]([Id]),
	CONSTRAINT [FK_ProductPriceInfo_RowStatus] FOREIGN KEY ([RowStatus]) REFERENCES [Lookups].[RowStatusInfo]([RowStatus])
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [IX_ProductPriceInfo_SequenceId] ON [Setup].[ProductPriceInfo] ([SequenceId])