CREATE TABLE [Lookups].[ExpenseTypeInfo]
(
	[ExpenseType] NVARCHAR(25) NOT NULL,
	[ExpenseTypeValue] NVARCHAR(25) NOT NULL,
	[SequenceId] INT NOT NULL,
	[RowStatus] NVARCHAR(1) NOT NULL DEFAULT 'A'
	CONSTRAINT [PK_Lookups_ExpenseTypeInfo] PRIMARY KEY CLUSTERED 
	(
		[ExpenseType] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	CONSTRAINT [FK_ExpenseTypeInfo_RowStatusInfo] FOREIGN KEY ([RowStatus]) REFERENCES [Lookups].[RowStatusInfo]([RowStatus])
) ON [PRIMARY];
