CREATE TABLE [Lookups].[LoanStatusInfo]
(
	[LoanStatus] NVARCHAR(10) NOT NULL,
	[LoanStatusValue] NVARCHAR(10) NOT NULL
	CONSTRAINT [PK_Lookups_LoanStatusInfo] PRIMARY KEY NONCLUSTERED
	(
		[LoanStatus] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY]
