CREATE TABLE [Lookups].[MeasureTypeInfo]
(
	[MeasureType] NVARCHAR(1) NOT NULL,
	[MeasureTypeValue] NVARCHAR(25) NOT NULL
	CONSTRAINT [PK_Lookups_MeasureTypeInfo] PRIMARY KEY NONCLUSTERED
	(
		[MeasureType] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY]