CREATE TABLE [Lookups].[PaymentMethodInfo]
(
	[PaymentMethod] NVARCHAR(10) NOT NULL,
	[PaymentMethodValue] NVARCHAR(10) NOT NULL
	CONSTRAINT [PK_Lookups_PaymentMethodInfo] PRIMARY KEY NONCLUSTERED
	(
		[PaymentMethod] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY]