CREATE TABLE [Lookups].[RowStatusInfo]
(
	[RowStatus] NVARCHAR(1) NOT NULL,
	[RowStatusValue] NVARCHAR(10) NOT NULL
	CONSTRAINT [PK_Lookups_RowStatusInfo] PRIMARY KEY NONCLUSTERED
	(
		[RowStatus] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY]
