CREATE TABLE [Lookups].[TimePeriodInfo]
(
	[TimePeriod] NVARCHAR(10) NOT NULL,
	[TimePeriodValue] NVARCHAR(10) NOT NULL,
	[RowStatus] NVARCHAR(1) NOT NULL DEFAULT 'A'
	CONSTRAINT [PK_Lookups_TimePeriodInfo] PRIMARY KEY CLUSTERED 
	(
		[TimePeriod] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	CONSTRAINT [FK_TimePeriodInfo_RowStatusInfo] FOREIGN KEY ([RowStatus]) REFERENCES [Lookups].[RowStatusInfo]([RowStatus])
) ON [PRIMARY];
