CREATE FUNCTION [Common].[udp_v1_ValidateGuid]
(
	@Id UNIQUEIDENTIFIER
)
RETURNS BIT
AS
BEGIN

	DECLARE @EmptyGuid UNIQUEIDENTIFIER;
	SET @EmptyGuid = CAST(CAST(0 AS BINARY) AS UNIQUEIDENTIFIER);
	
	RETURN CASE WHEN (@Id IS NULL OR @Id = @EmptyGuid) THEN 0 ELSE 1 END;
END
