CREATE FUNCTION [Common].[udp_v1_ValidateYear]
(
	@Year INT
)
RETURNS BIT
AS
BEGIN
	-- TODO GET MIN & MAX YEAR OF SYSTEM FROM SYSTEM SETTING TABLE
	RETURN CASE WHEN (@Year <= 2020 OR @Year > 2050) THEN 0 ELSE 1 END;
END
